### PR TITLE
Constify a raw 40ms timer

### PR DESCRIPTION
**Pull request by metalefty**
Probably it is missed in d9850d1 #166.

### CODE REVIEW

**Comment by metalefty** [comment]
@Nexarian The usage of `UPDATE_RETRY_TIMEOUT` is disappeared. Is this intended or is the code still needed?

https://github.com/neutrinolabs/xorgxrdp/commit/b90dd28c2995d62a5c6df73c4e1bbd5f50c7beb5

**Comment by metalefty** [comment]
The code is removed at https://github.com/neutrinolabs/xorgxrdp/commit/b93ad93881d9cbfaca1214c1fdb46208e12a4c1e

**Comment by matt335672** [comment]
Looks like a good idea to do this. I'm happy with it if Nex is.

**Comment by metalefty** [comment]
If the code is intendedly removed, I'll remove unused `UPDATE_RETRY_TIMEOUT`.

**Comment by metalefty** [comment]
It is removed at #274 so ping to @jsorg71, too.

**Comment by metalefty** [comment]
Anyway, UPDATE_RETRY_TIMEOUT is not in use at the moment, removed.

**Pull request merged**
