### PR TITLE
Bump version to v0.9.19

### PR DESCRIPTION
**Pull request by metalefty**

### CODE REVIEW

**Comment by matt335672** [comment]
LGTM - the bump for v0.2.18 is d81fe5f342b218cd8efb28007b14a73cc1bdc094, and this looks identical

**Comment by metalefty** [comment]
I created some cherry-pick PRs from devel to v0.9 branch. #232 is the last. 
Any other thoughts?

**Comment by matt335672** [comment]
I can't see anything else in devel which is worth taking over. The only other significant change from devel is 600095a2d5133a13409395b6629309506963672a, and you don't need that.

**Comment by metalefty** [comment]
That's right. Merging.

**Pull request merged**
