### PR TITLE
Add mappings for media keys

### LINKED ISSUE #211: XRDP Keyboard evdev support?
Is it possible to switch XRDP to evdev keyboard rules or at least make it compatible?

All ubuntu 20.04 flavors (gnome, xfce, ...) seem to use 'evdev' keyboards:
> setxkbmap -query -v
> Trying to build keymap using the following components:
> keycodes:   evdev+aliases(qwertz)
> types:      complete
> compat:     complete
> symbols:    pc+de+inet(evdev)
> geometry:   pc(pc105)
> rules:      evdev
> model:      pc105
> layout:     de

However when i connect to this same machines via XRDP i get a 'base' rule with a 'xfree86' setting:
> setxkbmap -query -v
> Trying to build keymap using the following components:
> keycodes:   xfree86+aliases(qwertz)
> types:      complete
> compat:     complete
> symbols:    pc+de
> geometry:   pc(pc104)
> rules:      base
> model:      pc104
> layout:     de

As far as i understand this might be intended to make it compatible for Xvnc sessions. However i don't use Xvnc sessions as i connect to Xorg sessions via xorgxrdp extensions.
So, how can i switch XRDP to evdev to make it behave exactly like it does on the X console?

My problem arises with certain applications (mostly remote consoles) that do work on the machine's X console as intended but having keyboard issues when i access my machine via XRDP. They all suffer the same problem of ignoring alt-gr keys (german keyboard @, \, ...) and actually no cursor keys - only cursor-down seems to be enter.
The same effect appears if i switch keyboard to 'evdev' in running XRDP session via `setxkbmap -rules evdev`
Then all applications have this same problem. So it seems to me that these applications won't play with 'base' mode but need 'evdev' rules?

So question is, what can be done to make XRDP play with 'evdev' rules. I tried this on ubuntu 20.04, xubuntu20.04 with xrdp 0.9.12 (ubuntu repos) and 0.9.18 built from source - all the same. Any ideas? 

Is this a bug or a limitation of the current implementation?
https://github.com/neutrinolabs/xrdp/issues/179 seems to imply that there is a way to switch to evdev rules (breaking Xvnc - but that would be ok for me) but it does not tell what needs to be done to achieve this. As this is quite old i'm not sure if it still applies.

### LINKED ISSUE #1725: Media keys have wrong keycode in XRDP session
OS: Lubuntu 20.04
Hyper-V vsock connection

It appears that the media keys have the wrong key codes when using the xrdp session (but they work fine with the basic session in Hyper-V)...

in the xrdp session the keycodes received for the media keys are wrong
<pre>
xev | sed -n 's/^.*state \([0-9].*\), keycode *\([0-9]\+\) *\(.*\), .*$/keycode \2 = \3, state = \1/p'
keycode 40 = (keysym 0x64, d), state = 0x10   <---Mute Key
keycode 40 = (keysym 0x64, d), state = 0x10
keycode 54 = (keysym 0x63, c), state = 0x10 <-- Volume Down
keycode 54 = (keysym 0x63, c), state = 0x10
keycode 56 = (keysym 0x62, b), state = 0x10 <-- Volume UP
keycode 56 = (keysym 0x62, b), state = 0x10
keycode 24 = (keysym 0x71, q), state = 0x10 <-- Back
keycode 24 = (keysym 0x71, q), state = 0x10
keycode 42 = (keysym 0x67, g), state = 0x10 <-- Play/Pause
keycode 42 = (keysym 0x67, g), state = 0x10
keycode 33 = (keysym 0x70, p), state = 0x10 <-- Forward
keycode 33 = (keysym 0x70, p), state = 0x10
</pre>

The xrdp-genkeymap (in the xrdp session) command generated a new .ini file which was not the same as the default km-**409.ini that came by default, however this still did not work. 

I attempted to set the key codes manually in the km-**409.ini file based on the output of  'xmodmap -pk' (in a basic session), 
<pre>
 121         0x1008ff12 (XF86AudioMute)      0x0000 (NoSymbol)       0x1008ff12 (XF86AudioMute)
 122         0x1008ff11 (XF86AudioLowerVolume)       0x0000 (NoSymbol)       0x1008ff11 (XF86AudioLowerVolume)
 123         0x1008ff13 (XF86AudioRaiseVolume)       0x0000 (NoSymbol)       0x1008ff13 (XF86AudioRaiseVolume)
</pre>
and
<pre>
Key121=269025042:0
Key122=269025041:0
Key123=269025043:0
</pre>

I don't know how to fix the wrong keycode issue for this..

### PR DESCRIPTION
**Pull request by sasha0552**
Related: neutrinolabs/xrdp#3022
Fixes: neutrinolabs/xrdp#1725
Fixes: #211

### CODE REVIEW

**Comment by tim-gromeyer** [comment]
Any plans on merging this?

**Comment by sasha0552** [comment]
Just a heads up, I have another branch that has been adapted for neutrinolabs/xrdp#3039. But those changes have not been tested yet.

https://github.com/sasha0552/xorgxrdp/tree/media-keys

I kind of dislike the fact that there is still special handling for certain keys.

I don't have much time these days, hopefully I can carve out more time for this and PR for relative input in the next week or so.

**Comment by matt335672** [comment]
@sasha0552 - I'll pick this one up if you don't mind.

I've found a few problems with neutrinolabs/xrdp#3039 in testing related directly to the (currently unused) keycode interface. I'll get those fixed in devel first.

**Comment by matt335672** [comment]
Superceded by #316 which is now merged.

**Pull request closed without merging**
