### PR TITLE
#endif typo on amd64

### PR DESCRIPTION
**Pull request by limadm**
This small typo is causing compilation problems on amd64_sse2.

### CODE REVIEW

**Comment by itamarjp** [comment]
@proski please review

**Comment by proski** [comment]
It's fixed in the `devel` branch. I think it's time to merge it into `master`. No need to create separate patches for the same issue.

**Comment by jsorg71** [comment]
I think I merged devel to master

**Comment by metalefty** [comment]
Already fixed in devel and devel has been merged into master, closing.

**Pull request closed without merging**
