### PR TITLE
Checking if glamor_egl_get_driver_name exists

### PR DESCRIPTION
**Pull request by laigor**
#237

### CODE REVIEW

**Comment by jsorg71** [comment]
Thanks, We do need a check for this.
This looks like it was added in 1.20.7 so lets use
#if XORG_VERSION_CURRENT >= XORG_VERSION_NUMERIC(1, 20, 7, 0, 0)
instead so we don't need to use PKG_CHECK_EXISTS(epoxy >= 1.5.4...

**Comment by matt335672** [comment]
@laigor - are you able to make the change @jsorg71 mentioned to your PR?

Thanks.

**Comment by jsorg71** [comment]
I can imagine a system with epoxy 1.5.4 and xorg-server 1.20.6 and this PR will still fail.
Lets check xorg-server version.
I created PR #239 for this.
Thanks for pointing this out.

**Comment by laigor** [comment]
> Thanks, We do need a check for this. This looks like it was added in 1.20.7 so lets use #if XORG_VERSION_CURRENT >= XORG_VERSION_NUMERIC(1, 20, 7, 0, 0) instead so we don't need to use PKG_CHECK_EXISTS(epoxy >= 1.5.4...

This is how the xorg xserver checks for the presence of the glamor_egl_get_driver_name function:
```
conf_data.set('GLAMOR_HAS_EGL_QUERY_DRIVER',
              epoxy_dep.found() and epoxy_dep.version().version_compare('>= 1.5.4') ? '1' : false)

```
[Please see this link](https://gitlab.freedesktop.org/xorg/xserver/-/blob/master/include/meson.build)

**Comment by jsorg71** [comment]
````
> conf_data.set('GLAMOR_HAS_EGL_QUERY_DRIVER',
>               epoxy_dep.found() and epoxy_dep.version().version_compare('>= 1.5.4') ? '1' : false)
````

xorg-server version 1.20.7+ does that to check to see if function eglGetDisplayDriverName() exists, not glamor_egl_get_driver_name().
The function we call glamor_egl_get_driver_name() always exists in xorg-server version 1.20.7+.  The check controls whether glamor_egl_get_driver_name() returns NULL or calls eglGetDisplayDriverName().

see
https://gitlab.freedesktop.org/xorg/xserver/-/blob/master/glamor/glamor_egl.c#L707

**Comment by jsorg71** [comment]
fixed  via #239

**Pull request closed without merging**
